BEGIN;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS ai_draft_id BIGINT UNIQUE REFERENCES ai_course_drafts(id) ON DELETE SET NULL;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS student_content JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS published_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_courses_ai_generated ON courses(ai_generated);
COMMIT;