"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Overview = {
  user:{firstName:string;lastName:string;level:string|null;objective:string|null;subscription:string;xp:number};
  stats:{enrolledCourses:number;completedCourses:number;completedLessons:number;quizAttempts:number;averageQuizScore:number;quizXp:number};
  continueCourse:any|null; recentLessons:any[]; recentQuizzes:any[]; certificates:any[]; badges:any[];
};
type LiveClass={id:number;title:string;starts_at:string;status:string};

export default function Dashboard(){
 const [data,setData]=useState<Overview|null>(null); const [classes,setClasses]=useState<LiveClass[]>([]);
 const [familyCode,setFamilyCode]=useState(""); const [codeBusy,setCodeBusy]=useState(false);
 const [loading,setLoading]=useState(true);
 useEffect(()=>{
   Promise.all([fetch("/api/v1/student/overview",{cache:"no-store"}),fetch("/api/live-classes",{cache:"no-store"})])
   .then(async ([o,c])=>{const od=await o.json();const cd=await c.json();if(o.status===401){window.location.href="/connexion";return;}if(od.success){setData(od.data);if(["premium","premium_famille","family"].includes(String(od.data.user.subscription||"").toLowerCase())){const f=await fetch("/api/v1/student/family-code",{method:"POST"});const fj=await f.json();if(fj.success)setFamilyCode(fj.data.code);}}if(cd.success)setClasses(cd.classes||[]);})
   .catch(()=>window.location.href="/connexion").finally(()=>setLoading(false));
 },[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/";}
 async function generateFamilyCode(){setCodeBusy(true);try{const r=await fetch("/api/v1/student/family-code",{method:"POST"});const j=await r.json();if(j.success)setFamilyCode(j.data.code);}finally{setCodeBusy(false);}}
 if(loading)return <main className="student-shell"><div className="student-container"><div className="empty-state">Chargement de ton espace…</div></div></main>;
 if(!data)return <main className="student-shell"><div className="student-container"><div className="empty-state">Impossible de charger ton espace.</div></div></main>;
 const name=data.user.firstName||"Élève";const resume=data.continueCourse;const nextClass=classes[0];
 const isFamily=["premium","premium_famille","family"].includes(String(data.user.subscription||"").toLowerCase());
 const progressPct=resume?Math.max(0,Math.min(100,Number(resume.progress)||0)):0;
 const nextClassTime=nextClass?new Date(nextClass.starts_at):null;
 const hasResume=Boolean(resume);
 return <main className="student-shell"><div className="student-container">
  <div className="student-hero"><div><span className="eyebrow">ESPACE ÉLÈVE</span><h1>Bonjour {name} 👋</h1><p>{data.user.level?`Niveau ${data.user.level} · `:""}{data.user.objective||"Continue ton parcours et progresse à ton rythme."}</p></div><div className="student-xp-card"><small>TON EXPÉRIENCE</small><strong>⭐ {data.user.xp} XP</strong><div className="xp-level-mini"><span>Niveau {Math.floor(data.user.xp/100)+1}</span><i><em style={{width:(data.user.xp%100)+"%"}} /></i><span>{100-(data.user.xp%100)} XP</span></div></div></div>
  <div className="student-welcome-strip"><div><span className="eyebrow">TON PARCOURS AUJOURD’HUI</span><b>{hasResume?"Reprends exactement où tu t’es arrêté.":"Choisis ton premier parcours et commence à progresser."}</b></div><Link href={hasResume?"/cours/"+resume.slug:"/cours"} className="btn btn-yellow">{hasResume?"Reprendre maintenant":"Choisir un cours"} →</Link></div>
  <div className="student-command-grid">
   <div className="student-command-card primary"><span className="command-icon">▶</span><div><small>PROCHAINE ACTION</small><b>{resume?progressPct>0?"Continue ton dernier cours":"Commence ton premier cours":"Choisis ton premier parcours"}</b><p>{resume?resume.title:"Découvre les parcours adaptés à ton niveau."}</p></div><Link href={resume?"/cours/"+resume.slug:"/cours"} className="command-arrow">→</Link></div>
   <div className="student-command-card"><span className="command-icon">🎯</span><div><small>OBJECTIF</small><b>{data.stats.quizAttempts>0?"Continue à t’entraîner":"Fais ton premier quiz"}</b><p>{data.stats.quizAttempts} quiz réalisés · {data.stats.averageQuizScore}% de moyenne</p></div><Link href="/quiz" className="command-arrow">→</Link></div>
   <div className="student-command-card"><span className="command-icon">🏆</span><div><small>PROGRESSION</small><b>{data.stats.completedCourses} parcours terminé{data.stats.completedCourses>1?"s":""}</b><p>{data.stats.completedLessons} leçons validées · {data.user.xp} XP</p></div><Link href="/dashboard" className="command-arrow">→</Link></div>
  </div>
  <div className="student-quick-nav"><Link href="/cours">📚 Mes cours</Link><Link href="/quiz">🧠 Mes quiz</Link><Link href="/classes">🎥 Classes live</Link><Link href="/parent">👪 Suivi famille</Link></div>
  <div className="student-stats"><div className="student-stat"><small>Cours suivis</small><strong>{data.stats.enrolledCourses}</strong><span>parcours actifs</span></div><div className="student-stat"><small>Leçons terminées</small><strong>{data.stats.completedLessons}</strong><span>étapes franchies</span></div><div className="student-stat"><small>Quiz réalisés</small><strong>{data.stats.quizAttempts}</strong><span>entraînements</span></div><div className="student-stat"><small>Score moyen</small><strong>{data.stats.quizAttempts?data.stats.averageQuizScore+"%":"—"}</strong><span>{data.stats.quizAttempts?"niveau de maîtrise":"Premier quiz à faire"}</span></div></div>
  {isFamily&&<div className="student-panel family-link" style={{marginBottom:20}}><span className="eyebrow">PREMIUM FAMILLE</span><h2 style={{marginTop:8}}>Ton code famille</h2><p>Partage ce code avec ton parent pour lui permettre de suivre ta progression, sans partager ton mot de passe.</p><div style={{display:"flex",gap:12,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:26,letterSpacing:3,color:"#061b46"}}>{familyCode||"—"}</strong><button className="btn btn-light" onClick={generateFamilyCode} disabled={codeBusy}>{codeBusy?"Génération…":"Actualiser le code"}</button></div></div>}
  <div className="student-grid"><div className="student-panel"><h2>▶ Reprendre mon apprentissage</h2>{resume?<div className="resume-card"><div className="resume-top"><div><span className="eyebrow">{resume.category}</span><h3>{resume.title}</h3><p>{resume.last_lesson_title||"Continuer le parcours"}</p></div><strong>{resume.progress}%</strong></div><div className="student-progress"><span style={{width:String(resume.progress)+"%"}} /></div><div className="resume-actions"><small>{resume.completed_lessons}/{resume.total_lessons} leçons terminées</small><Link className="btn btn-yellow" href={"/cours/"+resume.slug}>{resume.progress>0?"Continuer":"Commencer"} →</Link></div></div>:<div className="resume-card"><h3>Construis ton parcours</h3><p>Choisis un cours et commence ta progression.</p><Link className="btn btn-yellow" href="/cours">Découvrir les cours →</Link></div>}
   <h2 style={{marginTop:30}}>⚡ Activité récente</h2><div className="activity-list">{data.recentLessons.map(l=><div className="activity-item" key={"l-"+l.id}><div className="activity-icon">📖</div><div><b>{l.title}</b><small>{l.course_title} · {l.progress}%</small></div></div>)}{data.recentQuizzes.map(q=><div className="activity-item" key={"q-"+q.id}><div className="activity-icon">🧠</div><div><b>{q.quiz_title||"Quiz"}</b><small>{q.percentage}% · +{q.xp_gained} XP</small></div></div>)}{!data.recentLessons.length&&!data.recentQuizzes.length&&<div className="empty-state">Ton activité apparaîtra ici dès que tu commenceras à apprendre.</div>}</div>
  </div><div className="student-panel"><div className="progress-command"><div><span className="eyebrow">TON PARCOURS</span><h2>Chaque étape compte.</h2><p>{data.stats.completedCourses} parcours terminé{data.stats.completedCourses>1?"s":""} · {data.stats.quizXp} XP gagnés grâce aux quiz.</p></div><Link href={resume?"/cours/"+resume.slug:"/cours"} className="btn btn-light">{resume?"Continuer":"Découvrir"} →</Link></div><div className="learning-roadmap"><div className={"roadmap-step "+(data.stats.enrolledCourses>0?"done":"")}><span>1</span><b>Commencer</b><small>{data.stats.enrolledCourses>0?"Parcours choisi":"Choisir un parcours"}</small></div><div className={"roadmap-line "+(data.stats.completedLessons>0?"active":"")}></div><div className={"roadmap-step "+(data.stats.completedLessons>0?"done":"")}><span>2</span><b>Progresser</b><small>{data.stats.completedLessons} leçons validées</small></div><div className={"roadmap-line "+(data.stats.quizAttempts>0?"active":"")}></div><div className={"roadmap-step "+(data.stats.quizAttempts>0?"done":"")}><span>3</span><b>S’entraîner</b><small>{data.stats.quizAttempts} quiz réalisés</small></div><div className={"roadmap-line "+(data.stats.completedCourses>0?"active":"")}></div><div className={"roadmap-step "+(data.certificates.length>0?"done":"")}><span>4</span><b>Certifier</b><small>{data.certificates.length>0?data.certificates.length+" certificat"+(data.certificates.length>1?"s":""):"Parcours à 100 %"}</small></div></div><div className="achievement-head"><div><span className="eyebrow">ÉTAPES CLÉS</span><h2>🏅 Mes badges</h2></div><span className="achievement-count">{data.badges.filter(b=>b.unlocked).length}/{data.badges.length} débloqués</span></div><div className="badge-grid">{data.badges.map(b=><div key={b.id} className={"badge-item "+(b.unlocked?"":"locked")}><span>{b.icon}</span><b>{b.title}</b><small>{b.description}</small>{b.unlocked&&<em>✓ Débloqué</em>}</div>)}</div><h2 style={{marginTop:30}}>🎓 Mes certificats</h2><div className="certificate-list">{data.certificates.map(c=><div className="certificate-item" key={c.id}><span className="cert-icon">🎓</span><div><b>{c.course_title}</b><small>{new Date(c.issued_at).toLocaleDateString("fr-FR")}</small></div><Link className="student-link" href={"/verify/"+c.certificate_code}>Vérifier</Link></div>)}{!data.certificates.length&&<div className="empty-state">Termine un parcours à 100 % pour obtenir ton premier certificat.</div>}</div><h2 style={{marginTop:30}}>🎥 Prochaine classe</h2>{nextClass?<div className="resume-card"><span className="eyebrow">{nextClass.status==="live"?"🔴 EN DIRECT":"PROCHAINE CLASSE"}</span><h3>{nextClass.title}</h3><p>{nextClassTime?nextClassTime.toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short"}):""}</p><Link href="/classes" className="student-link">Voir les classes →</Link></div>:<div className="resume-card"><h3>Aucune classe programmée</h3><p>Les prochaines sessions apparaîtront ici.</p></div>}</div></div>
  <div style={{display:"flex",justifyContent:"space-between",gap:15,marginTop:25,flexWrap:"wrap"}}><Link href="/cours" className="btn btn-dark">📚 Explorer les cours</Link><Link href="/quiz" className="btn btn-light">🧠 S'entraîner avec les quiz</Link><button onClick={logout} className="btn btn-light">↪ Déconnexion</button></div>
 </div></main>;
}
